; PlatformIO Project Configuration File
; Firmware Arduino Mega - Parte de Eder (UART v2, puerta, barrera, EEPROM,
; SET_MODE). Ver SAID-ARCH-UART v2.0.0 y PDF 1 (Programación Arduino).

[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit PWM Servo Driver Library
    miguelbalboa/MFRC522
    chris--a/Keypad
    marcoschwartz/LiquidCrystal_I2C